# Generated by Django 5.0.3 on 2024-04-25 22:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='message',
            field=models.TextField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='file',
            field=models.FileField(upload_to='chatbot', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
        migrations.CreateModel(
            name='FileLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('1', 'Número Indisponível'), ('2', 'Dado Incorreto'), ('3', 'API Indisponível'), ('4', 'Erro Desconhecido')], max_length=30)),
                ('row', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('chatbotFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileLogChatBot', to='main.chatbot')),
            ],
        ),
    ]
